name: peprmint
channels: 
- conda-forge 
- salilab 
- hydroid
- tpeulen
- speleo3
dependencies:
- python>=3.9
- pytest
- boost-cpp=1.73.*      
- boost=1.73.*          
- seaborn
- pandas
- biopandas
- biopython
- ipywidgets
- scipy
- numpy
- tqdm
- xmltodict
- pathlib
- salilab::dssp
- pytables
- termcolor
- requests
- bs4
- pip
- lxml
- wordcloud
- nglview
- mdanalysis
- weasyprint==52.5
- openpyxl
- pymol-open-source
- tmalign
- voila
- configparser
- pip:
  - pbxplore 
  - freesasa 
  - vg
  - pandarallel
  - ipyfilechooser
  - pyphen==0.12.0
  - ipykernel
